name: Test deploy to BunnyCDN

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Deploy
        uses: ayeressian/bunnycdn-storage-deploy@master
        with:
          source: "e2e/test-dir"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.ACCOUNT_API_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
