name: Deploy to BunnyCDN
on:
  push:
    branches:
      - master # replace this with the branch you want to deploy from
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.0.2
        with:
          source: "build" # for create-react-app, the output directory is "build"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.ACCOUNT_API_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
